package com.example.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * This is a class that models an Account.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "account")
public class Account {
    /**
     * An id for this Account. You should use this as the Entity's ID.
     */
    @Column(name = "account_id")
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer account_id;
    /**
     * A username for this Account (must be unique and not blank)
     */
    @Column(name = "username")
    private String username;
    /**
     * A password for this account (must be over 4 characters)
     */
    @Column(name = "password")
    private String password;

    /**
     * When posting a new Account, the id can be generated by the database.
     * In that case, a constructor without account_id is needed.
     */
    public Account(String username, String password) {
        this.username = username;
        this.password = password;
    }
}
