package com.example.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * This is a class that models a Message.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "message")
public class Message {
    /**
     * An id for this message which will be automatically generated by the database.
     */
    @Column(name = "message_id")
    @Id
    @GeneratedValue
    private Integer message_id;
    /**
     * The id for the user who has posted this message.
     * We will assume that this is provided by the front-end of this application.
     */
    @Column(name = "posted_by")
    private Integer posted_by;
    /**
     * The text for this message- eg "this is my first post!".
     * Must be not blank and under 255 characters
     */
    @Column(name = "message_text")
    private String message_text;
    /**
     * The epoch time when this tweet was posted (number of seconds since Jan 1, 1970).
     * Longs are large enough to store this number.
     * We will assume that this number is provided by the front-end of this application.
     */
    @Column(name = "time_posted_epoch")
    private Long time_posted_epoch;

    /**
     * When posting a new message, the id can be generated by the database.
     * In that case, a constructor without message_id is needed.
     */
    public Message(Integer posted_by, String message_text, Long time_posted_epoch) {
        this.posted_by = posted_by;
        this.message_text = message_text;
        this.time_posted_epoch = time_posted_epoch;
    }
}
